### ISSUE TITLE
No Support for Protocol, Port and Base Path configuration for anypoint_apim_flexgateway resource

### ISSUE THREAD

**Issue by vaibhav-yenorkar** [salesforce/terraform-provider-anypoint#89]
We are using Terraform Anypoint Provider version 1.6.1 downloaded from Terraform Registry.

When we tried to create flexgateway resource using anypoint_apim_flexgateway, we found API is getting created with default protocol as HTTP, Port as 8081 and Base Path as '**/**'. We did not see any configuration option to override these values.

Can you please let us know when these enhancements will be available ?

**Comment by sabsfdc** [comment]
@soufi  - any comments on this please? Thanks

**Comment by soufi** [comment]
Hi @vaibhav-yenorkar 
Flex Gateway will use any port you tell it to when you create your configuration. The port should be added to the consumer url.

**Comment by vaibhav-yenorkar** [comment]
Thanks @soufi for suggesting to use consumer url.

I am able to set port, protocol and basepath using endpoint_proxy_uri property.

**Comment by soufi** [comment]
@sabsfdc can you please close this one ?
